window.SQ_PATCH_APP=(function(prev){return function(t){
  if(prev)t=prev(t);
  const R=(a,b,label)=>{if(!t.includes(a)){console.warn('SQ patch missing:',label);return}t=t.replace(a,b)};
  R("Bez životů a úplně offline.","Bez životů a bez účtu.","header offline text");
  R("<h3>📖 Vyber téma</h3>","<h3>📖 Co se v tomto předmětu učíš</h3><p class=\"muted\">Vyber si konkrétní téma. U každého máš vysvětlení, co si zapamatovat, radu k učení a test.</p>","subject heading");
  R("note:'Lehce, s příklady a po krocích.'","note:'Učivo, vysvětlení a procvičování pro 6. třídu.'","grade6 note");
  R("note:'Vysvětlení, příklady a testy pro 7. třídu.'","note:'Učivo, vysvětlení a procvičování pro 7. třídu.'","grade7 note");
  R("note:'Tvoje původní Uč se chytře verze pro 8. třídu.'","note:'Učivo, vysvětlení a procvičování pro 8. třídu.'","grade8 note");
  R("note:'Přehled, opakování a těžší testy pro 9. třídu.'","note:'Učivo, opakování a procvičování pro 9. třídu.'","grade9 note");
  R("function openSubject(s){subject=s;hideAll();document.getElementById('subjectScreen').classList.remove('hidden');document.getElementById('subjectTitle').textContent='📘 '+s;const topics=DATA[grade][term][s]||[];document.getElementById('topicInfo').textContent=`${GRADE_META[grade].label} • ${term}. pololetí • ${topics.length} témat`;const tip=STUDY_TIPS[s]||{how:'Projdi vysvětlení, zkus téma převyprávět vlastními slovy a potom udělej test.',plan:'10 min učení → test → oprava chyb.',tip:'⭐ Opakuj hlavně to, co se ti nepovedlo.'};document.getElementById('subjectTip').innerHTML=`<div class=\"subject-tip-mini\"><b>💡 Rychlá rada pro ${s}</b><br>${tip.how}<br><span class=\"muted\">${tip.plan}</span></div>`;const list=document.getElementById('topicList');list.innerHTML='';topics.forEach((t,idx)=>{const best=topicProgress[progressKey(grade,term,s,t.name)],b=document.createElement('button');b.innerHTML=`<b>${idx+1}. ${t.name}</b><span class=\"count\">${t.questions.length} základních otázek • ${best!==undefined?'nejlépe '+best+' %':'zatím bez výsledku'}</span>`;b.onclick=()=>openTopic(idx);list.appendChild(b)})}","function openSubject(s){subject=s;hideAll();document.getElementById('subjectScreen').classList.remove('hidden');document.getElementById('subjectTitle').textContent='📘 '+s;const topics=DATA[grade][term][s]||[];document.getElementById('topicInfo').textContent=`${GRADE_META[grade].label} • ${term}. pololetí • ${topics.length} témat. V každém tématu máš vysvětlení, rady a test s 15 otázkami.`;const tip=STUDY_TIPS[s]||{how:'Projdi vysvětlení, zkus téma převyprávět vlastními slovy a potom udělej test.',plan:'10 min učení → test → oprava chyb.',tip:'⭐ Opakuj hlavně to, co se ti nepovedlo.'};document.getElementById('subjectTip').innerHTML=`<div class=\"subject-tip-mini\"><b>💡 Rychlá rada pro ${s}</b><br>${tip.how}<br><span class=\"muted\">${tip.plan}</span></div>`;const list=document.getElementById('topicList');list.innerHTML='';topics.forEach((t,idx)=>{const best=topicProgress[progressKey(grade,term,s,t.name)],b=document.createElement('button');b.innerHTML=`<b>${idx+1}. ${t.name}</b><span class=\"count\">📖 vysvětlení • 💡 rada • 📝 test 15 otázek • ${best!==undefined?'nejlépe '+best+' %':'zatím bez výsledku'}</span>`;b.onclick=()=>openTopic(idx);list.appendChild(b)})}","subject cards");
  return t;
}})(window.SQ_PATCH_APP);
