window.SQ_PATCH_APP=(function(prev){return function(t){
  if(prev)t=prev(t);
  const R=(a,b,label)=>{if(!t.includes(a)){console.warn('SQ patch missing:',label);return}t=t.replace(a,b)};
  R("function topicQuestions(s,idx){const t=DATA[grade][term][s][idx],raw=uniqueByPrompt(t.questions),count=raw.length>6?6:raw.length;return shuffle(raw).slice(0,count).map(q=>variant(q,t.name))}","function topicQuestions(s,idx){\n const topics=DATA[grade][term][s]||[],t=topics[idx],target=15;\n if(!t)return [];\n const chosen=[],seen=new Set();\n const add=(q,topicName)=>{if(!q||seen.has(q[0]))return;seen.add(q[0]);chosen.push({q:variant(q,topicName),sub:s,topic:topicName})};\n shuffle(uniqueByPrompt(t.questions)).forEach(q=>add(q,t.name));\n if(chosen.length<target){\n  const related=[];\n  topics.forEach((other,j)=>{if(j===idx)return;const distance=Math.abs(j-idx);uniqueByPrompt(other.questions).forEach(q=>related.push({q,topic:other.name,distance}))});\n  related.sort((a,b)=>a.distance-b.distance||Math.random()-.5);\n  related.forEach(x=>{if(chosen.length<target)add(x.q,x.topic)});\n }\n return shuffle(chosen).slice(0,target)\n}","original topic->v2");
  R("<div class=\"topic-actions\"><button class=\"primary big-action\" onclick=\"startTopicTest()\">📝 Spustit test tohoto tématu</button></div>","<div class=\"topic-actions\"><button class=\"primary big-action\" onclick=\"startTopicTest()\">📝 Spustit test • 15 otázek</button><p class=\"muted\" style=\"margin:10px 0 0\">Nejdřív otázky z tohoto tématu, potom související učivo ze stejného předmětu. Bez opakování stejné otázky.</p></div>","original button->v2");
  R("</style>","\n/* V3: persistence, stats and mobile polish */\n.stats-dashboard{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:16px 0}\n.stats-card{background:linear-gradient(180deg,#0f1c30,#0b1729);border:1px solid rgba(107,162,255,.14);border-radius:18px;padding:17px;text-align:center}\n.stats-card b{display:block;font-size:27px;margin-top:7px}\n.subject-progress{margin:12px 0;padding:14px 15px;border-radius:16px;background:rgba(8,16,29,.52);border:1px solid rgba(255,255,255,.055)}\n.subject-progress .row{margin-bottom:8px}\n.mini-bar{height:9px;background:#08101d;border-radius:999px;overflow:hidden;border:1px solid rgba(255,255,255,.05)}\n.mini-fill{height:100%;background:linear-gradient(90deg,#4f8cff,#38d39f)}\n.level-line{margin:12px 0 4px}\n@media(max-width:600px){\n  button{min-height:48px}\n  .row>button{width:100%}\n  .answers button{font-size:16px;padding:16px 14px}\n  #q{font-size:21px;line-height:1.4}\n  #next{width:100%;position:sticky;bottom:10px;z-index:3}\n  .result-actions button{flex:1 1 100%}\n  .big-action{font-size:17px}\n  .stats-dashboard{grid-template-columns:repeat(2,1fr)}\n}\n</style>","css insert");
  R("<section id=\"result\" class=\"hidden card\"><div id=\"resultText\"></div><div id=\"breakdown\"></div><div id=\"recommendations\"></div><div class=\"result-actions\"><button id=\"retryTopicBtn\" class=\"hidden primary\" onclick=\"startTopicTest()\">🔁 Zkusit téma znovu</button><button id=\"backTopicBtn\" class=\"hidden\" onclick=\"openTopic(currentTopicIndex)\">📖 Zpět na vysvětlení</button><button onclick=\"backMenu()\">🏠 Zpět na předměty</button></div></section>","<section id=\"result\" class=\"hidden card\"><div id=\"resultText\"></div><div id=\"breakdown\"></div><div id=\"recommendations\"></div><div class=\"result-actions\"><button id=\"retryTopicBtn\" class=\"primary\" onclick=\"restartLastTest()\">🔁 Zkusit test znovu</button><button id=\"practiceMistakesBtn\" class=\"hidden\" onclick=\"startWeakness()\">🧠 Procvičit chyby</button><button id=\"backTopicBtn\" class=\"hidden\" onclick=\"openTopic(currentTopicIndex)\">📖 Zpět na vysvětlení</button><button onclick=\"backMenu()\">🏠 Zpět na předměty</button></div></section>","result actions");
  R("<section id=\"customTestScreen\" class=\"hidden\">","\n<section id=\"statsScreen\" class=\"hidden\">\n  <div class=\"card\">\n    <div class=\"row\"><h2>📊 Moje statistiky</h2><button onclick=\"backMenu()\">⬅ Zpět</button></div>\n    <div class=\"stats-dashboard\">\n      <div class=\"stats-card\">⭐ XP<b id=\"statsXp\">0</b></div>\n      <div class=\"stats-card\">🏆 Level<b id=\"statsLevel\">1</b></div>\n      <div class=\"stats-card\">✅ Správně<b id=\"statsCorrect\">0</b></div>\n      <div class=\"stats-card\">🔥 Nejlepší série<b id=\"statsBestStreak\">0</b></div>\n      <div class=\"stats-card\">📝 Dokončené testy<b id=\"statsTests\">0</b></div>\n      <div class=\"stats-card\">🧠 Uložené chyby<b id=\"statsMistakes\">0</b></div>\n    </div>\n    <div class=\"level-line\"><b>Postup do dalšího levelu</b> <span id=\"statsLevelProgress\" class=\"muted\"></span></div>\n    <div class=\"bar\"><div class=\"fill\" id=\"statsLevelFill\"></div></div>\n    <h3>📚 Postup v předmětech tohoto pololetí</h3>\n    <div id=\"statsSubjects\"></div>\n    <div class=\"result-actions\"><button class=\"primary\" onclick=\"startWeakness()\">🧠 Procvičit moje chyby</button></div>\n  </div>\n</section>\n\n<section id=\"customTestScreen\" class=\"hidden\">","stats screen");
  return t;
}})(window.SQ_PATCH_APP);
