window.SQ_PATCH_APP=(function(prev){return function(t){
  if(prev)t=prev(t);
  const R=(a,b,label)=>{if(!t.includes(a)){console.warn('SQ patch missing:',label);return}t=t.replace(a,b)};
  R("function uniqueByPrompt(arr){const seen=new Set();return arr.filter(item=>{const q=item.q||item;if(seen.has(q[0]))return false;seen.add(q[0]);return true})}","function uniqueByPrompt(arr){const seen=new Set();return arr.filter(item=>{const q=item.q||item,key=item.basePrompt||q[0];if(seen.has(key))return false;seen.add(key);return true})}","unique prompts");
  R("function hideAll(){['gradeSelect','home','menu','subjectScreen','topicScreen','game','result','customTestScreen'].forEach(id=>document.getElementById(id).classList.add('hidden'))}","function hideAll(){['gradeSelect','home','menu','subjectScreen','topicScreen','game','result','statsScreen','customTestScreen'].forEach(id=>document.getElementById(id).classList.add('hidden'))}","hide stats");
  R("function variant(q,topic){let st=safeParse(storageGet(VARIANT_KEY),{}),key=`${grade}|${term}|${subject}|${topic}|${q[0]}`,last=Number(st[key]??-1),v=[p=>p,p=>'Vyber správnou odpověď: '+p,p=>'Která možnost je správně? '+p,p=>'Rychlé opakování: '+p,p=>`Otázka z tématu „${topic}“: `+p,p=>'Zkus bez nápovědy: '+p],choices=v.map((_,i)=>i).filter(n=>n!==last),pick=choices[Math.floor(Math.random()*choices.length)];st[key]=pick;storageSet(VARIANT_KEY,JSON.stringify(st));return [v[pick](q[0]),q[1],[...q[2]],q[3]]}","function variant(q,topic,s=subject){let st=safeParse(storageGet(VARIANT_KEY),{}),key=`${grade}|${term}|${s}|${topic}|${q[0]}`,last=Number(st[key]??-1),v=[p=>p,p=>'Vyber správnou odpověď: '+p,p=>'Která možnost je správně? '+p,p=>'Rychlé opakování: '+p,p=>`Otázka z tématu „${topic}“: `+p,p=>'Zkus bez nápovědy: '+p],choices=v.map((_,i)=>i).filter(n=>n!==last),pick=choices[Math.floor(Math.random()*choices.length)];st[key]=pick;storageSet(VARIANT_KEY,JSON.stringify(st));return [v[pick](q[0]),q[1],[...q[2]],q[3]]}","variant subject");
  R("function topicQuestions(s,idx){\n const topics=DATA[grade][term][s]||[],t=topics[idx],target=15;\n if(!t)return [];\n const chosen=[],seen=new Set();\n const add=(q,topicName)=>{if(!q||seen.has(q[0]))return;seen.add(q[0]);chosen.push({q:variant(q,topicName),sub:s,topic:topicName})};\n shuffle(uniqueByPrompt(t.questions)).forEach(q=>add(q,t.name));\n if(chosen.length<target){\n  const related=[];\n  topics.forEach((other,j)=>{if(j===idx)return;const distance=Math.abs(j-idx);uniqueByPrompt(other.questions).forEach(q=>related.push({q,topic:other.name,distance}))});\n  related.sort((a,b)=>a.distance-b.distance||Math.random()-.5);\n  related.forEach(x=>{if(chosen.length<target)add(x.q,x.topic)});\n }\n return shuffle(chosen).slice(0,target)\n}","function topicQuestions(s,idx){\n const topics=DATA[grade][term][s]||[],t=topics[idx],target=15;\n if(!t)return [];\n const chosen=[],seen=new Set();\n const add=(q,topicName)=>{if(!q||seen.has(q[0]))return;seen.add(q[0]);chosen.push({q:variant(q,topicName,s),basePrompt:q[0],sub:s,topic:topicName})};\n shuffle(uniqueByPrompt(t.questions)).forEach(q=>add(q,t.name));\n if(chosen.length<target){\n  const related=[];\n  topics.forEach((other,j)=>{if(j===idx)return;const distance=Math.abs(j-idx);uniqueByPrompt(other.questions).forEach(q=>related.push({q,topic:other.name,distance}))});\n  related.sort((a,b)=>a.distance-b.distance||Math.random()-.5);\n  related.forEach(x=>{if(chosen.length<target)add(x.q,x.topic)});\n }\n return shuffle(chosen).slice(0,target)\n}","topic stable prompts");
  R("function allQuestions(){let all=[];SUBJECTS_BY_GRADE[grade].forEach(s=>{(DATA[grade][term][s]||[]).forEach(t=>t.questions.forEach(q=>all.push({q,sub:s,topic:t.name})))});return uniqueByPrompt(all)}","function allQuestions(){let all=[];SUBJECTS_BY_GRADE[grade].forEach(s=>{(DATA[grade][term][s]||[]).forEach(t=>t.questions.forEach(q=>all.push({q:variant(q,t.name,s),basePrompt:q[0],sub:s,topic:t.name})))});return uniqueByPrompt(all)}","all questions variants");
  return t;
}})(window.SQ_PATCH_APP);
