window.SQ_PATCH_APP=(function(prev){return function(t){
  if(prev)t=prev(t);
  const R=(a,b,label)=>{if(!t.includes(a)){console.warn('SQ patch missing:',label);return}t=t.replace(a,b)};
  R("const STORAGE={xp:'sq_all_xp',mistakes:'sq_all_mistakes',correct:'sq_all_correct',topicProgress:'sq_all_topic_progress'};","const STORAGE={xp:'sq_all_xp',mistakes:'sq_all_mistakes',correct:'sq_all_correct',topicProgress:'sq_all_topic_progress',tests:'sq_all_tests',bestStreak:'sq_all_best_streak'};","storage keys");
  R("function storageGet(k){try{return window.storageGet(k)}catch(e){return Object.prototype.hasOwnProperty.call(MEMORY_STORE,k)?MEMORY_STORE[k]:null}}","function storageGet(k){try{if(typeof window.storageGet==='function')return window.storageGet(k);return localStorage.getItem(k)}catch(e){return Object.prototype.hasOwnProperty.call(MEMORY_STORE,k)?MEMORY_STORE[k]:null}}","storage get");
  R("function storageSet(k,v){try{window.storageSet(k,v)}catch(e){MEMORY_STORE[k]=String(v)}}","function storageSet(k,v){try{if(typeof window.storageSet==='function')window.storageSet(k,v);else localStorage.setItem(k,String(v))}catch(e){MEMORY_STORE[k]=String(v)}}","storage set");
  R("function storageRemove(k){try{window.storageRemove(k)}catch(e){delete MEMORY_STORE[k]}}","function storageRemove(k){try{if(typeof window.storageRemove==='function')window.storageRemove(k);else localStorage.removeItem(k)}catch(e){delete MEMORY_STORE[k]}}","storage remove");
  R("let grade='8',term='1',subject='',currentTopicIndex=-1,currentTopic='',gameKind='',questions=[],i=0,score=0,streak=0,results={},xp=Number(storageGet(STORAGE.xp)||0),level=Math.floor(xp/100)+1,totalCorrect=Number(storageGet(STORAGE.correct)||0),mistakes=safeParse(storageGet(STORAGE.mistakes),[]),topicProgress=safeParse(storageGet(STORAGE.topicProgress),{});","let grade='8',term='1',subject='',currentTopicIndex=-1,currentTopic='',gameKind='',mode='',questions=[],i=0,score=0,streak=0,results={},xp=Number(storageGet(STORAGE.xp)||0),level=Math.floor(xp/100)+1,totalCorrect=Number(storageGet(STORAGE.correct)||0),totalTests=Number(storageGet(STORAGE.tests)||0),bestStreak=Number(storageGet(STORAGE.bestStreak)||0),mistakes=safeParse(storageGet(STORAGE.mistakes),[]),topicProgress=safeParse(storageGet(STORAGE.topicProgress),{}),lastCustomQuestion=null;","state vars");
  return t;
}})(window.SQ_PATCH_APP);
