window.SQ_PATCH_APP=(function(prev){return function(t){
  if(prev)t=prev(t);
  const R=(a,b,label)=>{if(!t.includes(a)){console.warn('SQ patch missing:',label);return}t=t.replace(a,b)};
  R("function startWeakness(){let arr=mistakes.filter(m=>m.grade===grade&&m.term===term).map(m=>({q:m.q,sub:m.sub,topic:m.topic}));arr=uniqueByPrompt(arr);if(!arr.length){alert('Z tohoto ročníku a pololetí zatím nemáš uložené chyby.');return}gameKind='weak';startGame(shuffle(arr).slice(0,30),'🧠 Procvičení chyb')}","function startWeakness(){let arr=mistakes.filter(m=>m.grade===grade&&m.term===term).map(m=>({q:variant(m.q,m.topic,m.sub),basePrompt:m.basePrompt||m.q[0],sub:m.sub,topic:m.topic}));arr=uniqueByPrompt(arr);if(!arr.length){alert('Z tohoto ročníku a pololetí zatím nemáš uložené chyby.');return}gameKind='weak';startGame(shuffle(arr).slice(0,30),'🧠 Procvičení chyb')}","weak variants");
  R("function startGame(qs,m){questions=uniqueByPrompt(qs);i=0;score=0;streak=0;results={};mode=m;hideAll();document.getElementById('game').classList.remove('hidden');renderQ()}","function startGame(qs,m){questions=uniqueByPrompt(qs);if(!questions.length){alert('Pro tento test nejsou dostupné žádné otázky.');backMenu();return}i=0;score=0;streak=0;results={};mode=m;hideAll();document.getElementById('game').classList.remove('hidden');renderQ()}","empty game guard");
  R("function answerQ(x,b,q,item){document.querySelectorAll('.answers button').forEach(z=>z.disabled=true);const s=subOf(item);results[s]??={ok:0,total:0};results[s].total++;if(x===q[1]){b.classList.add('ok');score++;results[s].ok++;streak++;totalCorrect++;const gain=10+(streak>=3?5:0);xp+=gain;removeMistake(grade,term,s,q[0]);document.getElementById('feedback').innerHTML=`✅ Správně! +${gain} XP<br><span class=\"muted\">${q[3]}</span>`}else{b.classList.add('bad');streak=0;document.querySelectorAll('.answers button').forEach(z=>{if(z.textContent===q[1])z.classList.add('ok')});document.getElementById('feedback').innerHTML=`❌ Správně je: <b>${q[1]}</b><br><span class=\"muted\">${q[3]}</span>`;addMistake(grade,term,s,item.topic||currentTopic,q)}level=Math.floor(xp/100)+1;save();update();document.getElementById('next').classList.remove('hidden')}","function answerQ(x,b,q,item){document.querySelectorAll('.answers button').forEach(z=>z.disabled=true);const s=subOf(item),basePrompt=item.basePrompt||q[0];results[s]??={ok:0,total:0};results[s].total++;if(x===q[1]){b.classList.add('ok');score++;results[s].ok++;streak++;bestStreak=Math.max(bestStreak,streak);totalCorrect++;const gain=10+(streak>=3?5:0);xp+=gain;if(gameKind!=='custom')removeMistake(grade,term,s,basePrompt);document.getElementById('feedback').innerHTML=`✅ Správně! +${gain} XP<br><span class=\"muted\">${q[3]}</span>`}else{b.classList.add('bad');streak=0;document.querySelectorAll('.answers button').forEach(z=>{if(z.textContent===q[1])z.classList.add('ok')});document.getElementById('feedback').innerHTML=`❌ Správně je: <b>${q[1]}</b><br><span class=\"muted\">${q[3]}</span>`;if(gameKind!=='custom')addMistake(grade,term,s,item.topic||currentTopic,q,basePrompt)}level=Math.floor(xp/100)+1;save();update();document.getElementById('next').classList.remove('hidden')}","answer stable mistakes");
  R("function addMistake(g,t,s,topic,q){if(!mistakes.some(m=>m.grade===g&&m.term===t&&m.sub===s&&m.q[0]===q[0]))mistakes.push({grade:g,term:t,sub:s,topic,q});mistakes=mistakes.slice(-500)}function removeMistake(g,t,s,prompt){mistakes=mistakes.filter(m=>!(m.grade===g&&m.term===t&&m.sub===s&&m.q[0]===prompt))}","function addMistake(g,t,s,topic,q,basePrompt=q[0]){if(!mistakes.some(m=>m.grade===g&&m.term===t&&m.sub===s&&(m.basePrompt||m.q[0])===basePrompt))mistakes.push({grade:g,term:t,sub:s,topic,q,basePrompt});mistakes=mistakes.slice(-500)}function removeMistake(g,t,s,prompt){mistakes=mistakes.filter(m=>!(m.grade===g&&m.term===t&&m.sub===s&&(m.basePrompt||m.q[0])===prompt))}","mistake ids");
  R("function save(){storageSet(STORAGE.xp,String(xp));storageSet(STORAGE.correct,String(totalCorrect));storageSet(STORAGE.mistakes,JSON.stringify(mistakes));storageSet(STORAGE.topicProgress,JSON.stringify(topicProgress))}","function save(){storageSet(STORAGE.xp,String(xp));storageSet(STORAGE.correct,String(totalCorrect));storageSet(STORAGE.tests,String(totalTests));storageSet(STORAGE.bestStreak,String(bestStreak));storageSet(STORAGE.mistakes,JSON.stringify(mistakes));storageSet(STORAGE.topicProgress,JSON.stringify(topicProgress))}","save stats");
  return t;
}})(window.SQ_PATCH_APP);
